---
title: "Clases"
author: "Jesus Mudarra Luján"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## La función cut

```{r}
iris_df <- iris
petals <- iris$Petal.Length
iris_df$div1 <- cut(petals, breaks = 5, right = FALSE)
iris_df$div2 <- cut(petals, breaks = ceiling(sqrt(length(petals))), right = FALSE)
iris_df$div3 <- cut(petals, breaks = c(1, 2, 3, 4, 5, 6, 7), right = FALSE)
iris_df$div4 <- cut(petals, breaks = 5, right = FALSE, labels = FALSE)
iris_df$div5 <- cut(petals, breaks = 5, right = FALSE,
                    labels = c("Peq", "Norm", "Gran", "XGran", "Gigan"))
iris_df
```

## Funciones para las tablas de frecuencias

```{r}
TablaFrecs = function(x, k, A, p){ 
  L = min(x)-p/2+A*(0:k)
  x_cut = cut(x, breaks = L, right = FALSE)
  intervals = levels(x_cut)
  mc = (L[1]+L[2])/2+A*(0:(k-1))
  Fr.abs = as.vector(table(x_cut)) 
  Fr.rel = round(Fr.abs/length(x), 4) 
  Fr.cum.abs = cumsum(Fr.abs) 
  Fr.cum.rel = cumsum(Fr.rel)
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel)
  tabla
  }

TablaFrecs.L = function(x, L, V){
  x_cut = cut(x, breaks = L, right = FALSE, include.lowest = V)
  intervals = levels(x_cut)
  mc = (L[1:(length(L)-1)]+L[2:length(L)])/2
  Fr.abs = as.vector(table(x_cut)) 
  Fr.rel = round(Fr.abs/length(x), 4)
  Fr.cum.abs = cumsum(Fr.abs)
  Fr.cum.rel = cumsum(Fr.rel)
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel)
  tabla
  }
```

La tabla de frecuencias de la longitud de los pétalos de *Iris* es:

```{r}
TablaFrecs(petals, k = 6, A = 1, p = 0.1)
TablaFrecs.L(petals, L = c(1, 3, 4, 5, 5.5, 6, 6.5, 7), V = FALSE)
```











