---
title: "Ejemplo Final"
author: "Jesus Mudarra Luján"
date: '2022-09-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ejemplo final

## Juntar color de ojos y pelo sin distinguir por sexo

```{r}
ftable(HairEyeColor)
male <- HairEyeColor[, , "Male"]
female <- HairEyeColor[, , "Female"]
data <- as.table(male + female)
```

## Manipulación de datos

```{r}
dimnames(data) = list(
  Pelo = c("Negro", "Castaño", "Pelirrojo", "Rubio"),
  Ojos = c("Marrones", "Azules", "Pardos", "Verdes")
)
data
```

## Diagrama de Mosaico

```{r}
mosaicplot(data, col = c("lightblue"), main = "Diagrama de Mosaico")
```

## Datos numéricos

```{r}
sum(data)
colSums(data)
rowSums(data)
round(prop.table(colSums(data)), 3)
round(prop.table(rowSums(data)), 3)
```

## Diagramas de barras

```{r}
barplot(prop.table(colSums(data)), ylim = c(0, 0.4),
        main = "Frecuencias relativas de colores de ojos",
        col = c("burlywood4", "lightblue", "orange3", "lightgreen"))
```

```{r}
barplot(prop.table(rowSums(data)), ylim = c(0, 0.5),
        main = "Frecuencias relativas de colores de cabello",
        col = c("black", "burlywood4", "red", "gold"))
```

## Frecuencias relativas globales y marginales

```{r}
round(prop.table(data), 3)
round(prop.table(data, margin = 1), 3) # marginal por filas
round(prop.table(data, margin = 2), 3) # marginal por columnas
```

```{r}
barplot(prop.table(data, margin = 1), beside = TRUE, ylim = c(0, 0.8),
        main = "Frecuencias relativas de colores de cabello\n para cada color de ojos",
        col = c("black", "burlywood4", "red", "gold"),
        legend.text = TRUE)
```

```{r}
barplot(t(prop.table(data, margin = 2)), beside = TRUE, ylim = c(0, 0.6), # traspuesta porque son columnas
        main = "Frecuencias relativas de colores de ojos\n para cada color de pelo",
        col = c("burlywood4", "lightblue", "orange3", "lightgreen"),
        legend.text = TRUE)
```
