---
title: "Carga de DF"
author: "Jesus Mudarra Luján"
date: '2022-09-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Carga de ficheros local

```{r}
df = read.table("../../data/bulls.dat", header = FALSE,
                col.names = c("breed", "sale_price", "shoulder",
                          "fat_free", "percent_ff", "frame_scale",
                          "back_fat", "sale_height", "sale_weight"),
                sep = "", dec = ".")
head(df)
```

## Carga desde URL

```{r}
# ya no funciona la url así que pruebo con otra
#df2 = read.table("https://maitra.public.iastate.edu/stat501/datasets/bulls.dat")
df2 = read.table("http://winterolympicsmedals.com/medals.csv", header = TRUE,
                 sep = ",")
head(df2)
str(df2)
```

```{r}
df3 <- read.table("../../data/olive.txt")
str(df3)
```

```{r}
write.table(df3, file = "../../data/olive2.txt", dec = ".")
df4 = read.table("../../data/olive2.txt")
head(df4)
```

# Crear un DF

```{r}
gender = c("H", "M", "M", "M", "H")
age = c(23, 45, 20, 30, 18)
family = c(2, 3, 4, 2, 5)
df5 = data.frame(genero = gender, edad = age, familia = family, stringsAsFactors = TRUE)
row.names(df5) = c("P1", "P2", "P3", "P4", "P5")
df5
str(df5)
dimnames(df5) = list(
  c("Antonio", "Ricardo", "JuanGabriel", "María", "Margarita"),
  c("Sexo", "Años", "MiembrosFamilia")
)
df5
df5 <- rbind(df5, c("H", 30, 1))
df5
df5$Sexo = as.character(df5$Sexo)
df5$Ingresos = c(10000, 12000, 15000, 12000, 20000, 10000)
```


```{r}
gender = c("H", "M", "M", "M", "H")
age = c(23, 45, 20, 30, 18)
family = c(2, 3, 4, 2, 5)
df5 = data.frame(genero = gender, edad = age, familia = family, stringsAsFactors = TRUE)
df5[df5$genero=="M", ] -> df_m
str(df_m)
df_m = droplevels(df_m) # borrar niveles sobrantes de todos los factores
str(df_m)
```

## Tidyverse

```{r}
library(tidyverse)
iris_petal = select(iris, starts_with("Petal"))
head(iris_petal)
iris_length = select(iris, ends_with("Length"))
head(iris_length)
```

## Subset

```{r}
setosa <- subset(iris, Species=="versicolor", select = c(1, 3)) -> versicolor
rownames(versicolor) = 1:nrow(versicolor)
head(versicolor, 5)
str(versicolor)
```
