---
title: "Distribución de Poisson"
author: "Jesus Mudarra Luján"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Distribución de Poisson

Supongamos que $X$ modela el número de errores por página que tiene un valor esperado $\lambda = 5$.

### En `R`

```{r}
l = 7
plot(0:20, dpois(x = 0:20, lambda= l))
ppois(0:20, l)
qpois(0.5, 5)
rpois(100, lambda = l) -> data
hist(data)
```

### En `Python`

```{python}
import numpy as np
from scipy.stats import poisson
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 1)
mu = 5
mean, var, skew, kurt = poisson.stats(mu, moments="mvsk")

print("Media = {}".format(mean))
print("Varianza = {}".format(var))
print("Sesgo = {}".format(skew))
print("Curtosis = {}".format(kurt))

x = np.arange(0, 12)
ax.plot(x, poisson.pmf(x,mu), "bo", ms=8, label="Poisson(0.8)")
ax.vlines(x, 0, poisson.pmf(x, mu), colors="b", lw=4, alpha=0.5)
ax.legend(loc="best", frameon=False)

plt.show()
```
